---
title: "2021-06-22-parks-analysis"
author: "Ben Leamon"
date: "2021-06-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2021-06-22 Tidy Tuesday: Parks
```{r}
tuesdata <- tidytuesdayR::tt_load("2021-06-22")
parks <- tuesdata$parks
library(tidyverse)
```

```{r setup, include=FALSE}
proj_path <- "2021-06-22-parks"
entry_caption <- "Busy week this week, so I settled for recreating one of the example charts."
```


## Innitial Ideas: 
Could be cool to do a slope graph, see how cities have changed between 2012 and 2020.
Could do this for budget, or for other metrics. 
Could be interesting to look at the top and bottom performers for both budget and equity (same as bloomberg article)


## A little cleaning
```{r}
parks <- parks %>%
  mutate(spend_per_resident_data = as.numeric(gsub("\\$", "",spend_per_resident_data)))
```


## Top and bottom performers for budget
```{r}
parks %>%
  filter(year == "2020") %>%
  select(year, city, spend_per_resident_data, spend_per_resident_points) %>%
  arrange(desc(spend_per_resident_points)) %>%
  slice(c(1:10, (n() - 10):n() )) %>%
  mutate(city = fct_reorder(city, spend_per_resident_points)) %>%
  ggplot(aes(spend_per_resident_points, city))+ 
  geom_point()
```
```{r}
width <- 6
title_font <- "Noto Sans Bold"
main_font <- "NotoSans"

theme_set(theme_minimal())
theme <- theme_update(
  text = element_text(family = main_font),
  plot.title = element_text(family = title_font, size = 14),
  plot.title.position = "plot",
  legend.position = "none",
  axis.title = element_text(size = 8),
  axis.text = element_text(size = 8),
  axis.title.x = element_text(family = main_font),
  axis.title.y = element_text(family = main_font),
  plot.caption = element_text(family = main_font, size = 8),
  plot.margin = margin(20,20,20,20)
  #plot.background = element_rect(fill = "#eceff4")
)

parks %>%
  filter(year == "2020") %>%
  select(year, city, spend_per_resident_data, spend_per_resident_points) %>%
  arrange(desc(spend_per_resident_data)) %>%
  slice(c(1:10, (n() - 10):n() )) %>%
  #mutate(full_marks = )%>%
  mutate(city = fct_reorder(city, spend_per_resident_data)) %>%
  ggplot(aes(spend_per_resident_data, city))+ 
  geom_point()+ 
  labs(
    title = "Which cities spend the most (and least) on parks?",
    subtitle = "Spending per resident on parks in top-ten and bottom-ten cities", 
    x = "Spending per Resident (USD)", 
    y = NULL
  )
  ggsave("figs/parks.png", device = "png",width = width, height = (width*.618))
```




```{r}
parks %>%
  filter(year == "2020") %>%
  #select(year, city, spend_per_resident_data, spend_per_resident_points) %>%
  arrange(desc(total_pct)) %>%
  slice(c(1:10, (n() - 10):n() )) %>%
  #mutate(full_marks = )%>%
  mutate(city = fct_reorder(city, total_pct)) %>%
  ggplot(aes(total_pct, city, size = spend_per_resident_data))+ 
  geom_point()
```
Look at spending vs total pct 

```{r}
parks %>%
  filter(year == "2020") %>%
  ggplot(aes(spend_per_resident_data, total_pct)) +
  geom_point()+
  coord_flip()
```

