---
title: "2021-05-25-mariokart-analysis"
author: "Ben Leamon"
date: "2021-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 2021-05-25 Tidy Tuesday: Mario Kart
```{r}
tuesdata <- tidytuesdayR::tt_load("2021-05-25")
```

```{r setup, include=FALSE}
proj_path <- "2021-05-25-mariokart"
records <- tuesdata$records
drivers <- tuesdata$drivers 
```

```{r}
library(tidyverse)
library(directlabels)
```


What do the record durations look like? 

How do the record durations compare between level? In other words, how fast did people get better at each level? 

## Maybe do a time series of all the scores, with branching lines for with and without shortcuts? 
```{r}
records %>%
  filter(track == "Luigi Raceway" & type == "Three Lap") %>%
  ggplot(aes(date, time, color = shortcut))+
  geom_point()
```

```{r}
records %>%
  filter(type == "Three Lap") %>%
  ggplot(aes(date, time, color = shortcut))+
  geom_point()+
  facet_wrap(~track)
```

```{r}
records %>%
  filter(type == "Single Lap") %>%
  ggplot(aes(date, time, color = shortcut))+
  geom_point()+
  facet_wrap(~track)
```
Why does it seem to be either or on this? 
```{r}
library(RColorBrewer)
library(ggrepel)
library(directlabels)
```

```{r}
width <- 6
title_font <- "Noto Sans Bold"
main_font <- "NotoSans"

theme_set(theme_minimal())
theme <- theme_update(
  text = element_text(family = main_font),
  plot.title = element_text(family = title_font, size = 14),
  plot.title.position = "plot",
  legend.position = "none",
  axis.title = element_text(size = 8),
  axis.text = element_text(size = 8),
  axis.title.x = element_text(family = main_font),
  axis.title.y = element_text(family = main_font),
  plot.caption = element_text(family = main_font, size = 8),
  plot.margin = margin(20,20,20,20)
  #plot.background = element_rect(fill = "#eceff4")
)


first_records <- records%>%
  filter(type == "Three Lap") %>%
  group_by(track) %>%
  filter(row_number()==1) %>%
  mutate(first_time = time) %>%
  select(track, first_time)

most_improved <- records %>% 
  filter(type == "Three Lap") %>%
  group_by(track, shortcut) %>%
  summarise(improvement = max(time) - min(time)) %>%
  ungroup() %>%
  slice_max(order_by = improvement, n = 5) 


adjusted_records <- records %>%
  inner_join(first_records, by="track") %>%
  filter(type == "Three Lap") %>%
  mutate(adjusted_time = time - first_time)
  #filter(track %in% c("Toad's Turnpike","Choco Mountain")) %>%
  
ggplot() +
  #All tracks
  geom_line(data = adjusted_records,
            aes(date, adjusted_time, group=interaction(track, shortcut)),
            color = "grey50",
            alpha = 0.35)+
  #Top five tracks 
 geom_line(data= subset(adjusted_records, interaction(track,shortcut) %in% interaction(most_improved$track, most_improved$shortcut)),
           aes(date, adjusted_time, color = track, group = interaction(track, shortcut)),
           show.legend = FALSE)+
  geom_dl(subset(adjusted_records, interaction(track,shortcut) %in% interaction(most_improved$track, most_improved$shortcut)),
          mapping = aes(date, adjusted_time, label = track, color = track), 
#          method =list(dl.trans(x = x+0.3),"last.points"))+
#          method = list('last.bumpup', cex = 1.3, hjust = 1))+
          method =list(dl.trans(x = x+0.3),"last.bumpup"))+
  scale_color_brewer(palette = "Set1")+
  #scale_x_date(expand=c(0,2055))+
  expand_limits(x = as.Date(c("1997-01-01", "2030-01-01")))+
  theme_minimal()+ 
  labs(
    title = "Mario Kart World Records Over Time",
    subtitle = "All levels have seen improvements, but some more than others.",
    x = NULL,
    y = "Decrease since first record (seconds)",
    caption = "Three-lap world records. Data from Tidy Tuesday."
    
  )
  ggsave("figs/mario.png", width = width, height = (width*.618))
```


## How many records do these people have? 