---
title: "coffee-analysis"
author: "Ben Leamon"
date: "16/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import libraries: 
```{r}
library(tidyverse)
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-07-07')
```
```{r}
coffee_ratings <- tuesdata$coffee_ratings
```

```{r}
ggplot(coffee_ratings, aes(country_of_origin, total_cup_points, color = species))+
  geom_jitter()+
  coord_flip()
```

```{r}
averages <- coffee_ratings %>%
  group_by(country_of_origin, species)%>%
  summarise(
    mean = mean(total_cup_points),
    min = min(total_cup_points),
    max = max(total_cup_points)
    )

  ggplot(averages, aes(country_of_origin, mean, color = species))+
    geom_point()+
    #geom_point(aes(country_of_origin, max, color = species))+
    coord_flip()+
    theme_light()
```

```{r}
averages <- coffee_ratings %>%
  group_by(country_of_origin)%>%
  summarise(
    mean = mean(total_cup_points),
    min = min(total_cup_points),
    max = max(total_cup_points)
    )

  ggplot(averages, aes(fct_reorder(country_of_origin,mean), mean))+
    geom_point()+
    #geom_point(aes(country_of_origin, max, color = species))+
    coord_flip()+
    theme_light()
```


