---
title: "2020-11-03-ikea-analysis"
author: "Ben Leamon"
date: "2020-11-04"
output: html_document
editor_options: chunk_output_type: console
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 2020-11-03 Tidy Tuesday: Ikea
```{r}
tuesdata <- tidytuesdayR::tt_load("2020-11-03")
```
```{r}
library(skimr)
tt_ikea <- tuesdata$ikea

ikea <- tt_ikea %>%
  select(-X1) %>%
  mutate(price_usd = price *0.27)
```

What categories are most common?
```{r}
ikea %>%
  count(category, sort = TRUE) %>%
  mutate(category = fct_reorder(category, n)) %>%
  ggplot(aes(n, category))+
  geom_col()+
  labs( title = 'Number of items per category',
    x = NULL, 
    y = NULL
  )+
  theme_minimal()
```

What is the distribution of prices within each category? 
```{r}
library(glue)
library(scales)
ikea %>%
  add_count(category, name = "category_total") %>%
  mutate(category = glue("{category} ({category_total})"),
        category = fct_reorder(category, price_usd)) %>%
  ggplot(aes(price_usd, category))+
  geom_boxplot()+
  scale_x_log10(labels = dollar) + 
  labs(x = "Price USD",
       y = NULL,
       title = "How expensive are items in each category?")+
  theme_minimal()
```

With ridges instead of boxplots
```{r}
library(ggridges)
ikea %>%
  add_count(category, name = "category_total") %>%
  mutate(category = glue("{category} ({category_total})"),
        category = fct_reorder(category, price_usd)) %>%
  ggplot(aes(price_usd, category))+
  geom_density_ridges()+
  scale_x_log10(labels = dollar) + 
  labs(x = "Price USD",
       y = NULL,
       title = "How expensive are items in each category?")+
  theme_minimal()
```

